# -*- coding:  utf-8 -*-

# file to test the library that generates the file

from adapters.builder_file_adapter import BuilderToFile
import datetime
import base64

adapterClass = 'AdapterFacturaxion'
type_file = 'txt'

data = [
    {
        "head":"CAB",
        "lines":[
            {
                "label":"NitEmisor",
                "code":"COD001",
                "value":"901187615",
                "type":"<class""str"">"
            },
            {
                "label":"NitAdquiriente",
                "code":"COD002",
                "value":"123456789",
                "type":"<class""str"">"
            },
            {
                "label":"TipoDocumento",
                "code":"COD003",
                "value":"F",
                "type":"<class""str"">"
            },
            {
                "label":"Version",
                "code":"COD004",
                "value":2,
                "type":"<class""int"">"
            },
            {
                "label":"AmbieteDestinoDocumento",
                "code":"COD005",
                "value":2,
                "type":"<class""int"">"
            }
        ]
    },
    {
        "head":"HDR",
        "lines":[
            {
                "label":"IdentificadorFactura",
                "code":"COD006",
                "value":"SETT4019",
                "type":"<class""str"">"
            },
            {
                "label":"Serie",
                "code":"COD007",
                "value":"SETT",
                "type":"<class""str"">"
            },
            {
                "label":"Folio",
                "code":"COD008",
                "value":"4019",
                "type":"<class""str"">"
            },
            {
                "label":"FechaEmision",
                "code":"COD009",
                "value":datetime.date(2020,
                10,
                19),
                "type":"<class""datetime.date"">"
            },
            {
                "label":"HoraEmision",
                "code":"COD010",
                "value":"01:52:05",
                "type":"<class""str"">"
            },
            {
                "label":"TimeZone",
                "code":"COD011",
                "value":"America/Bogota",
                "type":"<class""str"">"
            },
            {
                "label":"TipoFactura",
                "code":"COD012",
                "value":"01",
                "type":"<class""str"">"
            },
            {
                "label":"MetodoPago",
                "code":"COD013",
                "value":"ZZZ",
                "type":"<class""str"">"
            },
            {
                "label":"TerminoPago",
                "code":"COD014",
                "value":"",
                "type":"<class""str"">"
            },
            {
                "label":"DescripcionTerminoPago",
                "code":"COD015",
                "value":"",
                "type":"<class""str"">"
            },
            {
                "label":"FechaInicioPago",
                "code":"COD016",
                "value":datetime.date(2020,
                10,
                19),
                "type":"<class""datetime.date"">"
            },
            {
                "label":"FechaFinPago",
                "code":"COD017",
                "value":datetime.date(2020,
                10,
                19),
                "type":"<class""datetime.date"">"
            },
            {
                "label":"FormaPago",
                "code":"COD018",
                "value":"1",
                "type":"<class""str"">"
            },
            {
                "label":"LugarExpedicion",
                "code":"COD019",
                "value":"",
                "type":"<class""str"">"
            },
            {
                "label":"RegimenFiscalEmisor",
                "code":"COD020",
                "value":"48",
                "type":"<class""str"">"
            },
            {
                "label":"EjercicioFiscal ",
                "code":"COD021",
                "value":"",
                "type":"<class""str"">"
            },
            {
                "label":"EstatusDocumento ",
                "code":"COD022",
                "value":"",
                "type":"<class""str"">"
            },
            {
                "label":"NumeroCheque",
                "code":"COD023",
                "value":"",
                "type":"<class""str"">"
            },
            {
                "label":"Departamento ",
                "code":"COD024",
                "value":"",
                "type":"<class""str"">"
            },
            {
                "label":"Division",
                "code":"COD025",
                "value":"",
                "type":"<class""str"">"
            },
            {
                "label":"CentroCostos ",
                "code":"COD026",
                "value":"",
                "type":"<class""str"">"
            },
            {
                "label":"TipoOperacion",
                "code":"COD027",
                "value":"10",
                "type":"<class""str"">"
            },
            {
                "label":"NumeroPartidas",
                "code":"COD028",
                "value":2,
                "type":"<class""int"">"
            },
            {
                "label":"Fecha de inicio del periodo de facturación.",
                "code":"COD029",
                "value":"",
                "type":"<class""str"">"
            },
            {
                "label":"Hora de inicio del periodo de facturación.",
                "code":"COD030",
                "value":"",
                "type":"<class""str"">"
            },
            {
                "label":"Fecha de fin del periodo de facturación.",
                "code":"COD031",
                "value":"",
                "type":"<class""str"">"
            },
            {
                "label":"Hora de fin del periodo de facturación.",
                "code":"COD032",
                "value":"",
                "type":"<class""str"">"
            },
            {
                "label":"Identficador de Sucursal",
                "code":"COD033",
                "value":"",
                "type":"<class""str"">"
            },
            {
                "label":"Fecha efectiva de Salida de los bienes",
                "code":"COD034",
                "value":"",
                "type":"<class""str"">"
            },
            {
                "label":"Hora efectiva de Salida de los bienes",
                "code":"COD035",
                "value":"",
                "type":"<class""str"">"
            },
            {
                "label":"Identificador del Pago.",
                "code":"COD036",
                "value":"",
                "type":"<class""str"">"
            }
        ]
    },
    {
        "head":"MON",
        "lines":[
            {
                "label":"Divisa",
                "code":"COD037",
                "value":"COP",
                "type":"<class""str"">"
            },
            {
                "label":"TipoCambio",
                "code":"COD038",
                "value":1.0,
                "type":"<class""float"">"
            },
            {
                "label":"Subtotal",
                "code":"COD039",
                "value":525.0,
                "type":"<class""float"">"
            },
            {
                "label":"Descuento",
                "code":"COD040",
                "value":"0.00",
                "type":"<class""str"">"
            },
            {
                "label":"MotivoDescuento",
                "code":"COD041",
                "value":"",
                "type":"<class""str"">"
            },
            {
                "label":"Cargos",
                "code":"COD042",
                "value":"0.00",
                "type":"<class""str"">"
            },
            {
                "label":"Motivos de Cargos",
                "code":"COD043",
                "value":"",
                "type":"<class""str"">"
            },
            {
                "label":"Total",
                "code":"COD044",
                "value":624.75,
                "type":"<class""float"">"
            },
            {
                "label":"TotalImpuestosRetenidos",
                "code":"COD045",
                "value":99.75,
                "type":"<class""float"">"
            },
            {
                "label":"TotalImpuestosTrasladados",
                "code":"COD046",
                "value":99.75,
                "type":"<class""float"">"
            },
            {
                "label":"TotalPagoAnticipado",
                "code":"COD047",
                "value":"0.00",
                "type":"<class""str"">"
            },
            {
                "label":"MontoAPagar",
                "code":"COD048",
                "value":624.75,
                "type":"<class""float"">"
            },
            {
                "label":"ObservacionesFactura",
                "code":"COD049",
                "value":"",
                "type":"<class""str"">"
            },
            {
                "label":"ImporteConLetras",
                "code":"COD050",
                "value":"setecientos veinticuatro mil pesos",
                "type":"<class""str"">"
            },
            {
                "label":"FechaTasaCambio",
                "code":"COD051",
                "value":datetime.date(2020,
                10,
                18),
                "type":"<class""datetime.date"">"
            },
            {
                "label":"TotalBaseImpuestos",
                "code":"COD052",
                "value":525.0,
                "type":"<class""float"">"
            },
            {
                "label":"TotalBrutoMasImpuestos",
                "code":"COD053",
                "value":624.75,
                "type":"<class""float"">"
            },
            {
                "label":"Total Anticipos",
                "code":"COD054",
                "value":"0.00",
                "type":"<class""str"">"
            },
            {
                "label":"Tipo de Moneda a la cual se hace la conversión.",
                "code":"COD055",
                "value":"",
                "type":"<class""str"">"
            },
            {
                "label":"Divisa Adicional",
                "code":"COD056",
                "value":"",
                "type":"<class""str"">"
            },
            {
                "label":"Tasa de Cambio Secundaria.",
                "code":"COD057",
                "value":"",
                "type":"<class""str"">"
            },
            {
                "label":"Fecha en la que se fijó la tasa de cambio secundaria.",
                "code":"COD058",
                "value":"",
                "type":"<class""str"">"
            },
            {
                "label":"TotalImpuestosIVA",
                "code":"COD059",
                "value":99.75,
                "type":"<class""float"">"
            },
            {
                "label":"Monto Total Impuesto IC",
                "code":"COD060",
                "value":"",
                "type":"<class""str"">"
            },
            {
                "label":"Monto Total Impuesto ICA",
                "code":"COD061",
                "value":"",
                "type":"<class""str"">"
            },
            {
                "label":"Monto Total Impuesto INC",
                "code":"COD062",
                "value":"",
                "type":"<class""str"">"
            }
        ]
    },
    {
        "head":"DIR",
        "lines":[
            {
                "label":"Calificador",
                "code":"COD218",
                "value":"SE",
                "type":"<class""str"">"
            },
            {
                "label":"Nit",
                "code":"COD219",
                "value":"901187615",
                "type":"<class""str"">"
            },
            {
                "label":"Código Interno (Emisor)",
                "code":"COD220",
                "value":"",
                "type":"<class""str"">"
            },
            {
                "label":"Código Externo (Emisor)",
                "code":"COD221",
                "value":"",
                "type":"<class""str"">"
            },
            {
                "label":"Código Global (Emisor)",
                "code":"COD222",
                "value":"",
                "type":"<class""str"">"
            },
            {
                "label":"Nombre",
                "code":"COD223",
                "value":"BITS AMERICAS SAS",
                "type":"<class""str"">"
            },
            {
                "label":"Line",
                "code":"COD224",
                "value":"CL 122   7 A 18 OF 205",
                "type":"<class""str"">"
            },
            {
                "label":"Departamento",
                "code":"COD225",
                "value":"D.C.",
                "type":"<class""str"">"
            },
            {
                "label":"Ciudad",
                "code":"COD226",
                "value":"",
                "type":"<class""str"">"
            },
            {
                "label":"Municipio (Emisor)",
                "code":"COD227",
                "value":"BOGOTÁ, D.C.",
                "type":"<class""str"">"
            },
            {
                "label":"CodigoPais",
                "code":"COD228",
                "value":"CO",
                "type":"<class""str"">"
            },
            {
                "label":"Pais",
                "code":"COD229",
                "value":"Colombia",
                "type":"<class""str"">"
            },
            {
                "label":"Contacto Nombre (Emisor)",
                "code":"COD230",
                "value":"",
                "type":"<class""str"">"
            },
            {
                "label":"Contacto Teléfono (Emisor)",
                "code":"COD231",
                "value":"",
                "type":"<class""str"">"
            },
            {
                "label":"Contacto Email (Emisor)",
                "code":"COD232",
                "value":"",
                "type":"<class""str"">"
            },
            {
                "label":"Cedula Juridica (Emisor)",
                "code":"COD233",
                "value":"",
                "type":"<class""str"">"
            },
            {
                "label":"DigitoVerificador",
                "code":"COD234",
                "value":"0",
                "type":"<class""str"">"
            },
            {
                "label":"TipoOrganizacionJuridica",
                "code":"COD235",
                "value":"1",
                "type":"<class""str"">"
            },
            {
                "label":"ClaveIdentificadorTributario",
                "code":"COD236",
                "value":"01",
                "type":"<class""str"">"
            },
            {
                "label":"NombreIdentificadorTributario",
                "code":"COD237",
                "value":"IVA",
                "type":"<class""str"">"
            },
            {
                "label":"ObligacionesFiscales",
                "code":"COD238",
                "value":"O-23",
                "type":"<class""str"">"
            },
            {
                "label":"RegimenFiscal",
                "code":"COD239",
                "value":"05",
                "type":"<class""str"">"
            },
            {
                "label":"CodigoDepartamento",
                "code":"COD240",
                "value":"11",
                "type":"<class""str"">"
            },
            {
                "label":"CodigoMunicipio",
                "code":"COD241",
                "value":"11001",
                "type":"<class""str"">"
            },
            {
                "label":"CodigoPostal",
                "code":"COD242",
                "value":"94134",
                "type":"<class""str"">"
            },
            {
                "label":"CIIU",
                "code":"COD243",
                "value":"",
                "type":"<class""str"">"
            },
            {
                "label":"LenguajePais",
                "code":"COD244",
                "value":"es",
                "type":"<class""str"">"
            },
            {
                "label":"Porcentaje de los participantes del consorcio",
                "code":"COD245",
                "value":"",
                "type":"<class""str"">"
            },
            {
                "label":"Nota Adicional al Contacto",
                "code":"COD246",
                "value":"",
                "type":"<class""str"">"
            },
            {
                "label":"TipoDocumentoIdentidad",
                "code":"COD247",
                "value":"31",
                "type":"<class""str"">"
            },
            {
                "label":"Número de Matrícula Mercantil",
                "code":"COD248",
                "value":"",
                "type":"<class""str"">"
            }
        ]
    },
    {
        "head":"DIR",
        "lines":[
            {
                "label":"Calificador",
                "code":"COD066",
                "value":"BY",
                "type":"<class""str"">"
            },
            {
                "label":"Nit",
                "code":"COD067",
                "value":"123456789",
                "type":"<class""str"">"
            },
            {
                "label":"Código Interno (Receptor)",
                "code":"COD068",
                "value":"",
                "type":"<class""str"">"
            },
            {
                "label":"Código Externo (Receptor)",
                "code":"COD069",
                "value":"",
                "type":"<class""str"">"
            },
            {
                "label":"Código Global (Receptor)",
                "code":"COD070",
                "value":"",
                "type":"<class""str"">"
            },
            {
                "label":"Nombre",
                "code":"COD071",
                "value":"Deco Addict",
                "type":"<class""str"">"
            },
            {
                "label":"Line",
                "code":"COD072",
                "value":"AVENIDA PANAMERICANA CRA 32",
                "type":"<class""str"">"
            },
            {
                "label":"Departamento",
                "code":"COD073",
                "value":"Nariño",
                "type":"<class""str"">"
            },
            {
                "label":"Ciudad",
                "code":"COD074",
                "value":"",
                "type":"<class""str"">"
            },
            {
                "label":"Municipio (Receptor)",
                "code":"COD075",
                "value":"IPIALES",
                "type":"<class""str"">"
            },
            {
                "label":"CodigoPais",
                "code":"COD076",
                "value":"CO",
                "type":"<class""str"">"
            },
            {
                "label":"Pais",
                "code":"COD077",
                "value":"Colombia",
                "type":"<class""str"">"
            },
            {
                "label":"Contacto Nombre (Receptor)",
                "code":"COD078",
                "value":"Deco Addict",
                "type":"<class""str"">"
            },
            {
                "label":"Contacto Teléfono (Receptor)",
                "code":"COD079",
                "value":"(603)-996-3829",
                "type":"<class""str"">"
            },
            {
                "label":"Contacto Email (Receptor)",
                "code":"COD080",
                "value":"deco.addict82@example.com",
                "type":"<class""str"">"
            },
            {
                "label":"Cedula Juridica (Receptor)",
                "code":"COD081",
                "value":"",
                "type":"<class""str"">"
            },
            {
                "label":"DigitoVerificador",
                "code":"COD082",
                "value":"5",
                "type":"<class""str"">"
            },
            {
                "label":"TipoOrganizacionJuridica",
                "code":"COD083",
                "value":"1",
                "type":"<class""str"">"
            },
            {
                "label":"ClaveIdentificadorTributario",
                "code":"COD084",
                "value":"ZY",
                "type":"<class""str"">"
            },
            {
                "label":"NombreIdentificadorTributario",
                "code":"COD085",
                "value":"No causa",
                "type":"<class""str"">"
            },
            {
                "label":"ObligacionesFiscales",
                "code":"COD086",
                "value":"R-99-PN",
                "type":"<class""str"">"
            },
            {
                "label":"RegimenFiscal",
                "code":"COD087",
                "value":"48",
                "type":"<class""str"">"
            },
            {
                "label":"CodigoDepartamento",
                "code":"COD088",
                "value":"52",
                "type":"<class""str"">"
            },
            {
                "label":"CodigoMunicipio",
                "code":"COD089",
                "value":"52356",
                "type":"<class""str"">"
            },
            {
                "label":"CodigoPostal",
                "code":"COD090",
                "value":"524060",
                "type":"<class""str"">"
            },
            {
                "label":"CIIU",
                "code":"COD091",
                "value":"",
                "type":"<class""str"">"
            },
            {
                "label":"LenguajePais",
                "code":"COD092",
                "value":"es",
                "type":"<class""str"">"
            },
            {
                "label":"Porcentaje de los participantes del consorcio",
                "code":"COD093",
                "value":"",
                "type":"<class""str"">"
            },
            {
                "label":"Nota Adicional al Contacto",
                "code":"COD094",
                "value":"",
                "type":"<class""str"">"
            },
            {
                "label":"TipoDocumentoIdentidad",
                "code":"COD095",
                "value":"31",
                "type":"<class""str"">"
            },
            {
                "label":"Número de Matrícula Mercantil",
                "code":"COD096",
                "value":"",
                "type":"<class""str"">"
            }
        ]
    },
    {
        "head":"REF",
        "lines":[
            
        ]
    },
    {
        "head":"DET",
        "lines":[
            [
                {
                    "label":"Cantidad",
                    "code":"COD113",
                    "value":5,
                    "type":"<class""int"">"
                },
                {
                    "label":"UnidadDeMedida",
                    "code":"COD114",
                    "value":"94",
                    "type":"<class""str"">"
                },
                {
                    "label":"Descripcion",
                    "code":"COD115",
                    "value":"[FURN_8999] Three-Seat Sofa\nThree Seater Sofa with Lounger in Steel Grey Colour",
                    "type":"<class""str"">"
                },
                {
                    "label":"ValorUnitario",
                    "code":"COD116",
                    "value":90.0,
                    "type":"<class""float"">"
                },
                {
                    "label":"Importe",
                    "code":"COD117",
                    "value":90.0,
                    "type":"<class""float"">"
                },
                {
                    "label":"Cantidad Solicitada",
                    "code":"COD118",
                    "value":"",
                    "type":"<class""str"">"
                },
                {
                    "label":"Número Interno ",
                    "code":"COD119",
                    "value":"FURN_8999",
                    "type":"<class""str"">"
                },
                {
                    "label":"Número Cliente",
                    "code":"COD120",
                    "value":"",
                    "type":"<class""str"">"
                },
                {
                    "label":"Código EAN ",
                    "code":"COD121",
                    "value":"null",
                    "type":"<class""str"">"
                },
                {
                    "label":"Código UPC",
                    "code":"COD122",
                    "value":"null",
                    "type":"<class""str"">"
                },
                {
                    "label":"Número Orden de Compra",
                    "code":"COD123",
                    "value":"",
                    "type":"<class""str"">"
                },
                {
                    "label":"Posición Orden de Compra ",
                    "code":"COD124",
                    "value":"",
                    "type":"<class""str"">"
                },
                {
                    "label":"Color ",
                    "code":"COD125",
                    "value":"",
                    "type":"<class""str"">"
                },
                {
                    "label":"Estilo ",
                    "code":"COD126",
                    "value":"",
                    "type":"<class""str"">"
                },
                {
                    "label":"Talla ",
                    "code":"COD127",
                    "value":"",
                    "type":"<class""str"">"
                },
                {
                    "label":"Modelo ",
                    "code":"COD128",
                    "value":"",
                    "type":"<class""str"">"
                },
                {
                    "label":"LOTE",
                    "code":"COD129",
                    "value":"",
                    "type":"<class""str"">"
                },
                {
                    "label":"VENCE",
                    "code":"COD130",
                    "value":"",
                    "type":"<class""str"">"
                },
                {
                    "label":"REGISTRO CUM",
                    "code":"COD131",
                    "value":"",
                    "type":"<class""str"">"
                },
                {
                    "label":"Código del tipo de precio informado",
                    "code":"COD132",
                    "value":"",
                    "type":"<class""str"">"
                },
                {
                    "label":"Unidades Por Empaque",
                    "code":"COD133",
                    "value":"",
                    "type":"<class""str"">"
                },
                {
                    "label":"Marca",
                    "code":"COD134",
                    "value":"",
                    "type":"<class""str"">"
                },
                {
                    "label":"ClaveCodigoUtilizado",
                    "code":"COD135",
                    "value":"999",
                    "type":"<class""str"">"
                },
                {
                    "label":"CodigoProducto",
                    "code":"COD136",
                    "value":"FURN_8999",
                    "type":"<class""str"">"
                },
                {
                    "label":"Costo Muestras Comerciales",
                    "code":"COD137",
                    "value":"",
                    "type":"<class""str"">"
                },
                {
                    "label":"Código del vendedor correspondiente al\nartículo",
                    "code":"COD138",
                    "value":"",
                    "type":"<class""str"">"
                },
                {
                    "label":"Código del vendedor correspondiente a una subespecificación del artículo",
                    "code":"COD139",
                    "value":"",
                    "type":"<class""str"">"
                },
                {
                    "head":"TLT",
                    "lines":[
                        {
                            "label":"MontoTotalImpuesto",
                            "code":"COD081",
                            "value":85.5,
                            "type":"<class""float"">"
                        },
                        {
                            "label":"BaseImponible",
                            "code":"COD082",
                            "value":450.0,
                            "type":"<class""float"">"
                        },
                        {
                            "label":"ValorImpuesto",
                            "code":"COD083",
                            "value":85.5,
                            "type":"<class""float"">"
                        },
                        {
                            "label":"Unidad de Medida del Impuesto",
                            "code":False,
                            "value":"",
                            "type":"<class""str"">"
                        },
                        {
                            "label":"Identificación de la unidad de medida",
                            "code":False,
                            "value":"",
                            "type":"<class""str"">"
                        },
                        {
                            "label":"Valor del Impuesto por Unidad",
                            "code":False,
                            "value":"0.00",
                            "type":"<class""str"">"
                        },
                        {
                            "label":"TarifaImpuesto",
                            "code":"COD084",
                            "value":19.0,
                            "type":"<class""float"">"
                        },
                        {
                            "label":"ClaveImpuesto",
                            "code":"COD085",
                            "value":"01",
                            "type":"<class""str"">"
                        },
                        {
                            "label":"NombreImpuesto",
                            "code":"COD086",
                            "value":"IVA",
                            "type":"<class""str"">"
                        }
                    ]
                },
                {
                    "head":"TLR",
                    "lines":[
                        {
                            "label":"MontoTotalImpuesto",
                            "code":"COD081",
                            "value":85.5,
                            "type":"<class""float"">"
                        },
                        {
                            "label":"BaseImponible",
                            "code":"COD082",
                            "value":450.0,
                            "type":"<class""float"">"
                        },
                        {
                            "label":"ValorImpuesto",
                            "code":"COD083",
                            "value":85.5,
                            "type":"<class""float"">"
                        },
                        {
                            "label":"TarifaImpuesto",
                            "code":"COD084",
                            "value":19.0,
                            "type":"<class""float"">"
                        },
                        {
                            "label":"ClaveImpuesto",
                            "code":"COD085",
                            "value":"06",
                            "type":"<class""str"">"
                        },
                        {
                            "label":"NombreImpuesto",
                            "code":"COD086",
                            "value":"ReteFuente",
                            "type":"<class""str"">"
                        }
                    ]
                }
            ],
            [
                {
                    "label":"Cantidad",
                    "code":"COD113",
                    "value":5,
                    "type":"<class""int"">"
                },
                {
                    "label":"UnidadDeMedida",
                    "code":"COD114",
                    "value":"94",
                    "type":"<class""str"">"
                },
                {
                    "label":"Descripcion",
                    "code":"COD115",
                    "value":"[FURN_8220] Four Person Desk\nFour person modern office workstation",
                    "type":"<class""str"">"
                },
                {
                    "label":"ValorUnitario",
                    "code":"COD116",
                    "value":15.0,
                    "type":"<class""float"">"
                },
                {
                    "label":"Importe",
                    "code":"COD117",
                    "value":15.0,
                    "type":"<class""float"">"
                },
                {
                    "label":"Cantidad Solicitada",
                    "code":"COD118",
                    "value":"",
                    "type":"<class""str"">"
                },
                {
                    "label":"Número Interno ",
                    "code":"COD119",
                    "value":"FX008",
                    "type":"<class""str"">"
                },
                {
                    "label":"Número Cliente",
                    "code":"COD120",
                    "value":"",
                    "type":"<class""str"">"
                },
                {
                    "label":"Código EAN ",
                    "code":"COD121",
                    "value":"null",
                    "type":"<class""str"">"
                },
                {
                    "label":"Código UPC",
                    "code":"COD122",
                    "value":"null",
                    "type":"<class""str"">"
                },
                {
                    "label":"Número Orden de Compra",
                    "code":"COD123",
                    "value":"",
                    "type":"<class""str"">"
                },
                {
                    "label":"Posición Orden de Compra ",
                    "code":"COD124",
                    "value":"",
                    "type":"<class""str"">"
                },
                {
                    "label":"Color ",
                    "code":"COD125",
                    "value":"",
                    "type":"<class""str"">"
                },
                {
                    "label":"Estilo ",
                    "code":"COD126",
                    "value":"",
                    "type":"<class""str"">"
                },
                {
                    "label":"Talla ",
                    "code":"COD127",
                    "value":"",
                    "type":"<class""str"">"
                },
                {
                    "label":"Modelo ",
                    "code":"COD128",
                    "value":"",
                    "type":"<class""str"">"
                },
                {
                    "label":"LOTE",
                    "code":"COD129",
                    "value":"",
                    "type":"<class""str"">"
                },
                {
                    "label":"VENCE",
                    "code":"COD130",
                    "value":"",
                    "type":"<class""str"">"
                },
                {
                    "label":"REGISTRO CUM",
                    "code":"COD131",
                    "value":"",
                    "type":"<class""str"">"
                },
                {
                    "label":"Código del tipo de precio informado",
                    "code":"COD132",
                    "value":"",
                    "type":"<class""str"">"
                },
                {
                    "label":"Unidades Por Empaque",
                    "code":"COD133",
                    "value":"",
                    "type":"<class""str"">"
                },
                {
                    "label":"Marca",
                    "code":"COD134",
                    "value":"",
                    "type":"<class""str"">"
                },
                {
                    "label":"ClaveCodigoUtilizado",
                    "code":"COD135",
                    "value":"999",
                    "type":"<class""str"">"
                },
                {
                    "label":"CodigoProducto",
                    "code":"COD136",
                    "value":"FX008",
                    "type":"<class""str"">"
                },
                {
                    "label":"Costo Muestras Comerciales",
                    "code":"COD137",
                    "value":"",
                    "type":"<class""str"">"
                },
                {
                    "label":"Código del vendedor correspondiente al\nartículo",
                    "code":"COD138",
                    "value":"",
                    "type":"<class""str"">"
                },
                {
                    "label":"Código del vendedor correspondiente a una subespecificación del artículo",
                    "code":"COD139",
                    "value":"",
                    "type":"<class""str"">"
                },
                {
                    "head":"TLT",
                    "lines":[
                        {
                            "label":"MontoTotalImpuesto",
                            "code":"COD081",
                            "value":14.25,
                            "type":"<class""float"">"
                        },
                        {
                            "label":"BaseImponible",
                            "code":"COD082",
                            "value":75.0,
                            "type":"<class""float"">"
                        },
                        {
                            "label":"ValorImpuesto",
                            "code":"COD083",
                            "value":14.25,
                            "type":"<class""float"">"
                        },
                        {
                            "label":"Unidad de Medida del Impuesto",
                            "code":False,
                            "value":"",
                            "type":"<class""str"">"
                        },
                        {
                            "label":"Identificación de la unidad de medida",
                            "code":False,
                            "value":"",
                            "type":"<class""str"">"
                        },
                        {
                            "label":"Valor del Impuesto por Unidad",
                            "code":False,
                            "value":"0.00",
                            "type":"<class""str"">"
                        },
                        {
                            "label":"TarifaImpuesto",
                            "code":"COD084",
                            "value":19.0,
                            "type":"<class""float"">"
                        },
                        {
                            "label":"ClaveImpuesto",
                            "code":"COD085",
                            "value":"01",
                            "type":"<class""str"">"
                        },
                        {
                            "label":"NombreImpuesto",
                            "code":"COD086",
                            "value":"IVA",
                            "type":"<class""str"">"
                        }
                    ]
                },
                {
                    "head":"TLR",
                    "lines":[
                        {
                            "label":"MontoTotalImpuesto",
                            "code":"COD081",
                            "value":14.25,
                            "type":"<class""float"">"
                        },
                        {
                            "label":"BaseImponible",
                            "code":"COD082",
                            "value":75.0,
                            "type":"<class""float"">"
                        },
                        {
                            "label":"ValorImpuesto",
                            "code":"COD083",
                            "value":14.25,
                            "type":"<class""float"">"
                        },
                        {
                            "label":"TarifaImpuesto",
                            "code":"COD084",
                            "value":19.0,
                            "type":"<class""float"">"
                        },
                        {
                            "label":"ClaveImpuesto",
                            "code":"COD085",
                            "value":"06",
                            "type":"<class""str"">"
                        },
                        {
                            "label":"NombreImpuesto",
                            "code":"COD086",
                            "value":"ReteFuente",
                            "type":"<class""str"">"
                        }
                    ]
                }
            ]
        ]
    },
    {
        "head":"TAX",
        "lines":[
            {
                "label":"MontoTotalImpuesto",
                "code":"COD175",
                "value":99.75,
                "type":"<class""float"">"
            },
            {
                "label":"BaseImponible",
                "code":"COD176",
                "value":525.0,
                "type":"<class""float"">"
            },
            {
                "label":"ValorImpuesto",
                "code":"COD177",
                "value":99.75,
                "type":"<class""float"">"
            },
            {
                "label":"Unidad de Medida del Impuesto",
                "code":"COD178",
                "value":"",
                "type":"<class""str"">"
            },
            {
                "label":"Identificación de la unidad de medida",
                "code":"COD179",
                "value":"",
                "type":"<class""str"">"
            },
            {
                "label":"Valor del Impuesto por Unidad",
                "code":"COD180",
                "value":"0.00",
                "type":"<class""str"">"
            },
            {
                "label":"TarifaImpuesto",
                "code":"COD181",
                "value":"19",
                "type":"<class""str"">"
            },
            {
                "label":"ClaveImpuesto",
                "code":"COD182",
                "value":"01",
                "type":"<class""str"">"
            },
            {
                "label":"NombreImpuesto",
                "code":"COD183",
                "value":"IVA",
                "type":"<class""str"">"
            }
        ]
    },
    {
        "head":"TIR",
        "lines":[
            {
                "label":"Monto Total Impuesto",
                "code":"COD184",
                "value":99.75,
                "type":"<class""float"">"
            },
            {
                "label":"Base Imponible sobre la que se calcula el valor del tributo",
                "code":"COD185",
                "value":525.0,
                "type":"<class""float"">"
            },
            {
                "label":"Valor del Impuesto: producto del porcentaje aplicado sobre la base imponible",
                "code":"COD186",
                "value":99.75,
                "type":"<class""float"">"
            },
            {
                "label":"Tarifa del Impuesto",
                "code":"COD187",
                "value":"19",
                "type":"<class""str"">"
            },
            {
                "label":"Clave de Impuesto",
                "code":"COD188",
                "value":"06",
                "type":"<class""str"">"
            },
            {
                "label":"Nombre del Impuesto",
                "code":"COD189",
                "value":"ReteFuente",
                "type":"<class""str"">"
            }
        ]
    }
]
separator = '|'

file = BuilderToFile.prepare_file_for_submission(
    type_file,
    adapterClass,
    data,
    separator
)

print("action_test_connection\n")
result = ''
if file:
    result = file.decode('utf-8')
print(f"{result}")
